version: '3.8'

services:
  web:
    build: ./
    command: gunicorn --worker-class eventlet -w 1 --bind unix:/tmp/gunicorn.sock --access-logfile=./logs/access.log --error-logfile=./logs/errors.log src.restapi.wsgi:app
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env

